version: '3.9'
services:
  cassandra:
    image: cassandra:latest
    container_name: my-cassandra
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=test_cluster
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:

